---
- name: This playbook installs httpd and apache2 packages
  hosts: all
  become: true
  # gather_facts: no

  tasks:
  - name: install package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    tags: install apache2
   
  - name: start service httpd, if not started
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    tags: start apache2 

  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    tags: install apache2

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
    tags: start apache2
 
  - name: copy index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: "0666"
